### ISSUE TITLE
When install hr sample schema via sqlplus, needs some considerations

### ISSUE THREAD

**Issue by miyamam** [oracle-samples/db-sample-schemas#20]
When I installed HR sample schema via sqlplus on Windows server, I did following steps to avoid errors.
- session configuration
`alter session set "_ORACLE_SCRIPT"=true;
`
- password quate with "" 

If this information is helpful, could you add Readme note.

**Comment by mikesmithers** [comment]
I also hit the issue with **_&pass_** not being double-quoted in the install scripts ( in my case both HR and CO schemas).
This was whilst running the relevant _<schema>_install.sql_ script in SQLDeveloper (21.2.1.204) on my OCI Free Tier (19c ) database as ADMIN. 
I needed to change the CREATE USER statement (using HR as an example) from
`CREATE USER hr IDENTIFIED BY  &pass
               DEFAULT TABLESPACE &tbs
               QUOTA UNLIMITED ON &tbs;`
to 
`CREATE USER hr IDENTIFIED BY **"**&pass**"**
               DEFAULT TABLESPACE &tbs
               QUOTA UNLIMITED ON &tbs;`

I believe that making this minor change to the relevant install scripts would fix the issue for most (any ?) Oracle client tool where these scripts might reasonably be executed from.

**Comment by gvenzl** [comment]
Hi @miyamam,

Regarding the `_ORACLE_SCRIPT` parameter, you are most likely encountering this because you are trying to install a sample schema into the `CDB$ROOT` rather than the PDB.
Please install the sample schemas only in a PDB, not in the `CDB$ROOT`.

Both, your and @mikesmithers point about the `""` is well taken, we will add this to the scripts.

**Comment by gvenzl** [comment]
Fixed.
