### ISSUE TITLE
WARNING: These Samples should not be installed with an Oracle DB having the EBS Applications system.

### ISSUE THREAD

**Issue by LordDumoss** [oracle-samples/db-sample-schemas#21]
Oracle is getting SRs on these being installed in an EBS Applications system.
I believe providing a warning here would be the best. So...

WARNING: Do not install the Oracle Samples into the same database as Oracle EBS Applications 12.2.x system.

                  These sample schema objects are not edition defined and will cause errors during adop patching process.

                  If these objects are installed in an EBS 11.5.10.2 or 12.1.3 system, they should be removed before upgrading to 
                  12.2.x.
                        
                  If you want to use these open and modify these sample scripts to use a different set of schemas.
                  EXAMPLE: scott_hr,  scott_oe,  etc...

**Comment by LordDumoss** [comment]
NOTE Also EBS Applications does not use nor support this code being used.

**Comment by gvenzl** [comment]
Hi @LordDumoss,

It is impractical to provide a warning for every existing schema model that these **sample** schemas shouldn't be installed into.

Instead, the ReadMe points out that these schemas are there to only demonstrate the capabilities of Oracle Database

> 1. Introduction
The [Oracle Database Documentation](https://docs.oracle.com/en/database/oracle/oracle-database/index.html) and other resources use these sample schemas to demonstrate the capabilities of [Oracle Database](https://www.oracle.com/database/) and the SQL and PL/SQL languages. You can download and install these schemas in your database environments to learn about Oracle Database functionality or try the examples in the documentation. These schemas are provided for free.

and the schemas are provided under the MIT license with a clear disclaimer:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

I'd be curious to learn more about the SRs that customers are filing, perhaps there is a more generic messaging that we can put into the ReadMe that will clarify their purpose.

Please reach out to me internally if you think this is still an issue and we can discuss how to best approach this.
